### ISSUE TITLE
Remove keep_all VariableConfig option?

### ISSUE THREAD

**Issue by samvanstroud** [umami-hep/umami-preprocessing#24]
@IvanOleksiyuk noticed this is unsued, let's remove it if we don't need it.

https://github.com/umami-hep/umami-preprocessing/blob/3ce3d2c1cf1254b4033b6dd1f5ff754ae5c1a33c/upp/classes/variable_config.py#L11

**Comment by IvanOleksiyuk** [comment]
I found that it is actually used to keep all the variables in the test dataset (If I am understanding it correctly) but the usage quite implicit so option should stay for now. I think I could probably also make use of it for the umami integration.

**Comment by IvanOleksiyuk** [comment]
It is used here to be more specific: https://github.com/umami-hep/umami-preprocessing/blob/02f80fa22550903b36f329ff2c3ec825af40f553/upp/classes/preprocessing_config.py#L104

**Comment by IvanOleksiyuk** [comment]
Please close this issue
