### ISSUE TITLE
Issues during resampling

### ISSUE THREAD

**Issue by jirahandler** [umami-hep/umami-preprocessing#33]
Hi,

There seems to be issues during running the preprocessing chain. I'm using running instructions as described [here](https://umami-hep.github.io/umami-preprocessing//run/)

and I'm using this shell directive from within singularity (for convenience):
`preprocess --config single-b.yaml --split=all`

The `single-b.yaml` script is the one that's found [here](https://gitlab.cern.ch/sgoswami/umami/-/blob/run3gn2papdips/single-b.yaml)

The error is as follows and has probably to do with the tolerance value [here]( https://github.com/umami-hep/umami-preprocessing/blob/main/upp/classes/components.py#L82) . The countup method is used (as seen in the single-b.yaml file). Would you have any fixes? Thx! Also a small part of getting this package to work seamlessly uses this [fix](https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/umami/-/merge_requests/740#note_7252512) (second fix).

```bash
INFO     Sampling fraction chosen for each component automatically...
Traceback (most recent call last):
  File "/usr/local/bin/preprocess", line 8, in <module>
    sys.exit(main())
  File "/data/sgoswami/umami/.local/lib/python3.8/site-packages/upp/main.py", line 113, in main
    run_pp(args)
  File "/data/sgoswami/umami/.local/lib/python3.8/site-packages/upp/main.py", line 76, in run_pp
    resampling.run()
  File "/data/sgoswami/umami/.local/lib/python3.8/site-packages/upp/stages/resampling.py", line 249, in run
    self.set_component_sampling_fractions()
  File "/data/sgoswami/umami/.local/lib/python3.8/site-packages/upp/stages/resampling.py", line 219, in set_component_sampling_fractions
    raise ValueError(
ValueError: [bold red]Sampling fraction of 1.006>1 is needed for component highpt_zprime_bjets This is not supported for countup method.
```

**Comment by IvanOleksiyuk** [comment]
Hi sorry for a late response. Is this issue still relevant? If so can you describe it more detail. What sample were you applying it to?

**Comment by jirahandler** [comment]
HI, the issue could still be relevant to someone facing this error, but it's now an non-issue on my side. As far as I remember, the only samples this script was working on was standard tt-bar and Z' samples used in DIPS training. The issue can be closed.

**Comment by rkuesters** [comment]
Hi @jirahandler 

Can you elaborate a bit more on your fix?
I am having the same error at the moment

Cheers, Roman

**Comment by samvanstroud** [comment]
Hi @rkuesters, for now can you try using `method: pdf` instead of `countup`?
