### ISSUE TITLE
Why use flavour_label?

### ISSUE THREAD

**Issue by zcapjdb** [umami-hep/umami-preprocessing#5]
The jet `flavour_label` is something we define in the pre-processing and use within training. However this means that we can't directly evaluate a file from the TDD as it won't have a `flavour_label`. Should we not jus use the `HadronConeExclTruthLabelID` everywhere?

**Comment by samvanstroud** [comment]
Probably we could but we need to keep an option to define and use the `flavour_label` for the cases where the labelling is more complicated the a simple mapping of one variable, see https://github.com/umami-hep/atlas-ftag-tools/blob/main/ftag/flavours.yaml for exampels

**Comment by samvanstroud** [comment]
@zcapjdb should we close this based on https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/salt/-/merge_requests/114?
