### ISSUE TITLE
support for custom jet labeling scheme

### ISSUE THREAD

**Issue by jburzy** [umami-hep/umami-preprocessing#51]
It would be useful if there was a way to override the `flavours.yaml` in the `ftag` package to allow for sampling jets of an arbitrary class (e.g. for training discriminants beyond flavour tagging). Currently having to check out that package and modify that file directly is not an ideal workflow.

**Comment by samvanstroud** [comment]
Sounds like a good idea, would you like to work on it?

You could wrap [these lines](https://github.com/umami-hep/atlas-ftag-tools/blob/main/ftag/flavour.py#L84) in a new method `FlavourContainer.from_yaml(path)`

Then we should add a [global config option](https://github.com/umami-hep/umami-preprocessing/blob/main/upp/classes/preprocessing_config.py#L90) to this package which can be used to provide a custom path.

Finally we'd need to instantiate our default/custom `FlavourContainer` in the same class, store it as a member, and then access it in places like this: https://github.com/umami-hep/umami-preprocessing/blob/main/upp/classes/components.py#L124

**Comment by jburzy** [comment]
Sure, I'll take a stab at it in the next weeks
