### ISSUE TITLE
Change version to v0.2.0

### ISSUE THREAD

**Issue by rkuesters** [umami-hep/umami-preprocessing#61]
I tried to use version v0.2.0 for running upp, but I observed that always version v0.0.6 is installed, even with the latest pulls. 
I assume this line is responsible for this, I changed it to v0.2.0 and the correct version is installed. 

Furthermore v0.2.0 is not available when trying to install upp from the packages. 

Tagging @samvanstroud @nikitapond 

https://github.com/umami-hep/umami-preprocessing/blob/5f4a9ee20e4af39e7dab9649a50f224caebf8607/upp/__init__.py#L4

**Comment by samvanstroud** [comment]
Thanks for reporting @rkuesters, fixed here https://github.com/umami-hep/umami-preprocessing/commit/4697d39dc74de3c4b8c0113fa09af045f4e9958b
