### ISSUE TITLE
Enforcing fixed u/b/c ratio between lowpt and highpt regions

### ISSUE THREAD

**Issue by mtanasin** [umami-hep/umami-preprocessing#8]
Pdf and Countup sampling, in order to work properly, need a fixed u/b/c ratio in the lowpt and higpt regions. Otherwise, you end up with sketchy distributions such as the one attached.

It would be probably beneficial to enforce a fixed ratio in the configuration, to prevent the users from making this mistake.

![train_pt_btagJes](https://github.com/umami-hep/umami-preprocessing/assets/53352844/dd949e27-0842-4169-b485-b883824d6a67)

**Comment by samvanstroud** [comment]
Should be fixed by https://github.com/umami-hep/umami-preprocessing/pull/14
